name: Auto Push to Main

on:
  workflow_dispatch: # manual trigger (you can also add push/pull_request as needed)

jobs:
  push:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.MY_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set remote with PAT
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Abhiram-Sharma/activity.git

      - name: Push to main
        run: |
          git push origin main
