name: Automated Commits (10AM & 10PM IST)

on:
  schedule:
    - cron: '30 4,16 * * *'  # 10AM & 10PM IST
  workflow_dispatch:

jobs:
  commit-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Abhiram-Sharma"
          git config user.email "ab23.ar39@gmail.com"

      - name: Make 5 Dummy Commits
        run: |
          for i in {1..5}
          do
            echo "Commit $i at $(date -u)" >> commits.log
            git add commits.log
            git commit -m "🤖 Auto-commit $i on $(date -u)" || echo "No changes to commit"
          done

      - name: Push Changes Using PAT
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Abhiram-Sharma/activity.git
          git push origin main
